---
- name: Load git config
  command: git config --global core.excludesfile ~/.gitignore

- name: "ZSH | Download"
  git:
    repo: "git://github.com/robbyrussell/oh-my-zsh.git"
    dest: "~/.oh-my-zsh"

- name: "ZSH | Download theme"
  git:
    repo: "https://github.com/denysdovhan/spaceship-prompt.git"
    dest: "~/.oh-my-zsh/custom/themes/spaceship-prompt/"

- name: "ZSH | Download plugins zsh-completions"
  git:
    repo: "git://github.com/zsh-users/zsh-completions"
    dest: "~/.oh-my-zsh/custom/plugins/zsh-completions/"

- name: "ZSH | Download plugins zsh-syntax-highlighting"
  git:
    repo: "git://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/"

- name: "ZSH | Download plugins zsh-homestead"
  git:
    repo: "https://github.com/flemzord/zsh-homestead.git"
    dest: "~/.oh-my-zsh/custom/plugins/zsh-homestead/"


- name: "ZSH | Copy config"
  template:
    src: "templates/zshrc.j2"
    dest: "~/.zshrc"

- name: "ZSH | Define default shell"
  command: "chsh -s /bin/zsh"
