- name: "FISH | Download"
  get_url:
    url: https://get.oh-my.fish
    dest: "{{ downloads_dir }}/install.fish"

- name: "FISH | Install FISH"
  command: "fish {{ downloads_dir }}/install.fish"

- name: "FISH | Copy config"
  template:
    src: "templates/config.fish.j2"
    dest: "~/.config/fish/config.fish"

- name: Test for line
  sudo: true
  shell: grep "^/usr/local/bin/fish" /etc/shells
  register: test_grep

- name: add fish in shells
  sudo: true
  lineinfile: 
    dest: /etc/shells 
    line: "/usr/local/bin/fish"
  when: test_grep.stdout != ""

- name: "FISH | Define default shell"
  sudo: true
  command: "chsh -s /usr/local/bin/fish"

- name: "FISH | Install fzf"
  command: omf install fzf
  args:
    executable: /usr/local/bin/fish